  ocis:
    image: owncloud/ocis:5
    user: 1280:1280
    ports:
      - 9500:9200
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: https://cloud.yourdomain.com
      OCIS_LOG_LEVEL: error # make oCIS less verbose
      PROXY_TLS: false # do not use SSL between reverse proxy and oCIS
      OCIS_INSECURE: false
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      PROXY_ENABLE_BASIC_AUTH: false
      # admin user password
      # IDM_ADMIN_PASSWORD: "t8wp32JV6TpZeSgo" # this overrides the admin password from the configuration file
      # make settings service available to oCIS Hello
      SETTINGS_GRPC_ADDR: 0.0.0.0:9191
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142 # make the REVA gateway accessible to the app drivers
      # email server (if configured)
      NOTIFICATIONS_SMTP_HOST: ""
      NOTIFICATIONS_SMTP_PORT: "465"
      NOTIFICATIONS_SMTP_SENDER: ""
      NOTIFICATIONS_SMTP_USERNAME: "contact@yourdomain.com"
      NOTIFICATIONS_SMTP_PASSWORD: ""
      NOTIFICATIONS_SMTP_AUTHENTICATION: "LOGIN"
      NOTIFICATIONS_SMTP_INSECURE: "false"
      # PROXY_TLS is set to "false", the download url has no https
      STORAGE_USERS_DATA_GATEWAY_URL: http://ocis:9200/data
      # separate directory for thumbnails
      THUMBNAILS_FILESYSTEMSTORAGE_ROOT: /var/lib/ocis-thumbnails
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_SYSTEM_DRIVER: ocis
      STORAGE_USERS_S3NG_ENDPOINT: "https://s3.eu-central-003.backblazeb2.com"
      STORAGE_USERS_S3NG_REGION: "eu-central-003"
      STORAGE_USERS_S3NG_ACCESS_KEY: ""
      STORAGE_USERS_S3NG_SECRET_KEY: ""
      STORAGE_USERS_S3NG_BUCKET: ""
      PROXY_AUTOPROVISION_ACCOUNTS: true
      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      OCIS_OIDC_ISSUER: https://auth.yourdomain.com/realms/R1
      PROXY_OIDC_REWRITE_WELLKNOWN: true
      GRAPH_USERNAME_MATCH: none
      GRAPH_ASSIGN_DEFAULT_USER_ROLE: false
      OCIS_EXCLUDE_RUN_SERVICES: idp
      PROXY_USER_CS3_CLAIM: username
      WEB_OIDC_CLIENT_ID: ocis
      PROXY_USER_OIDC_CLAIM: preferred_username
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml 
      
      
      
    volumes:
      - /root/owncloud/ocis-config:/etc/ocis
      - /root/owncloud/ocis-data:/var/lib/ocis
      - /root/owncloud/thumbnails:/var/lib/ocis-thumbnails
      - /root/owncloud/ocis-config:/etc/ocis/csp.yaml
    logging:
      driver: "local"
    restart: always

